services:
  app:
    image: ${{ steps.login-ecr.outputs.registry }}/trinity-repo:${{ github.sha }}
    container_name: catch-ping-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    env_file:
      - .env
