services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local
    env_file:
      - ctc.env
    depends_on:
      - test_db
    networks:
      - ctc-network

  test_db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - ctc.env
    networks:
      - ctc-network

networks:
  ctc-network:
    driver: bridge

volumes:
  db_data: