services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: catch-ping-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    env_file:
      - .env