spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${LOCAL_DATASOURCE_URL}
    username: ${LOCAL_DATASOURCE_USERNAME}
    password: ${LOCAL_DATASOURCE_PASSWORD}
---
spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        generate_statistics: true  # Hibernate 통계 활성화
        order_updates: true # 동일한 엔티티 INSERT 문 정렬 최적화
        order_inserts: true
        jdbc:
          fetch_size: 1000 # 데이터 패치 크기
          batch_size: 1000 # 배치 크기
    open-in-view: false  # OSIV 끄기 (가능하면 끄는 것이 성능적으로 유리)

---
spring:
  shell:
    interactive:
      enabled: true

---
logging:
  level:
    org.hibernate.SQL: DEBUG  # SQL 쿼리 출력
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # 바인딩 파라미터 로그
    org.hibernate.engine.jdbc.batch.internal.BatchingBatch: DEBUG  # 배치 쿼리 로그
    com.zaxxer.hikari: DEBUG  # HikariCP 상태 출력

---
common:
  seat:
    available:
      count: 1