spring:
  profiles:
    active: local
---
spring:
  datasource:
    url: ${COMMON_DATASOURCE_URL}
    username: ${COMMON_DATASOURCE_USERNAME}
    password: ${COMMON_DATASOURCE_PASSWORD}

    hikari:
      connection-test-query: SELECT 1  # ?????? ?? ???
---
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
kakao:
  api:
    token-url: "https://kauth.kakao.com/oauth/token"
    client-id: ${KAKAO_API_KEY}
    redirect-uri: ${KAKAO_REDIRECT_URI}
    user-info-url: "https://kapi.kakao.com/v2/user/me"
    grant-type: "authorization_code"
    logout-url: "https://kapi.kakao.com/v1/user/logout"