server:
  tomcat:
    max-threads: 300   # 동시 처리 쓰레드 수
    max-connections: 10000  # 최대 연결 수

spring:
  datasource:
    url: ${PROD_DATASOURCE_URL}
    username: ${PROD_DATASOURCE_USERNAME}
    password: ${PROD_DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: 100
      minimum-idle: 10
      idle-timeout: 60000
      max-lifetime: 1800000
      connection-timeout: 30000
---
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        jdbc:
          fetch_size: 1000 # 데이터 패치 크기
          batch_size: 2000 # 배치 크기

---
spring:
  shell:
    interactive:
      enabled: false

---
logging:
  level:
    org.hibernate.SQL: DEBUG  # SQL 로그 비활성화
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # 파라미터 로그 비활성화
    org.hibernate.engine.jdbc.batch.internal.BatchingBatch: DEBUG  # 배치 로그 비활성화
    com.zaxxer.hikari: DEBUG  # HikariCP 관련 경고만 출력

---
common:
  seat:
    available:
      count: 1