spring:
  profiles:
    active: local
---
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
---
kakao:
  api:
    token-url: "https://kauth.kakao.com/oauth/token"
    client-id: ${KAKAO_API_KEY}
    redirect-uri: ${KAKAO_REDIRECT_URI}
    user-info-url: "https://kapi.kakao.com/v2/user/me"
    grant-type: "authorization_code"
    logout-url: "https://kapi.kakao.com/v1/user/logout"
    access-token-validation-url: "https://kapi.kakao.com/v1/user/access_token_info"
---
swagger:
  server-url:
    local: http://localhost:8080
    production: https://api.catchping.com
  group:
    auth:
      paths: /api/auth/**
    seat:
      paths: /api/seats/**
    fcm:
      paths: /api/fcmTokens/**
    restaurant:
      paths: /api/restaurants/**
    search:
      paths: /api/search/**
    reservation:
      paths: /api/reservations/**
    user:
      paths: /api/users/**
    notification:
      paths: /api/notifications/**

springdoc:
  api-docs:
    path: /api-docs # OpenAPI 명세 기본 경로
  swagger-ui:
    path: /swagger-ui.html # Swagger UI 기본 경로
---
firebase:
  project-id: catchping-fcmserver
  credentials: ${FIREBASE_CREDENTIALS}

ai:
  api:
    url: "http://10.0.172.33:5000/recommend"


